export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESOLVE = 'LOGIN_RESOLVE';
export const LOGIN_REJECT = 'LOGIN_REJECT';

export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_RESOLVE = 'SIGN_UP_RESOLVE';
export const SIGN_UP_REJECT = 'SIGN_UP_REJECT';

export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_RESOLVE = 'FORGOT_PASSWORD_RESOLVE';
export const FORGOT_PASSWORD_REJECT = 'FORGOT_PASSWORD_REJECT';

export const VERIFY_USER_REQUEST = 'VERIFY_USER_REQUEST';
export const VERIFY_USER_RESOLVE = 'VERIFY_USER_RESOLVE';
export const VERIFY_USER_REJECT = 'VERIFY_USER_REJECT';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_RESOLVE = 'RESET_PASSWORD_RESOLVE';
export const RESET_PASSWORD_REJECT = 'RESET_PASSWORD_REJECT';

export const VERIFY_OTP_REQUEST = 'VERIFY_OTP_REQUEST';
export const VERIFY_OTP_RESOLVE = 'VERIFY_OTP_RESOLVE';
export const VERIFY_OTP_REJECT = 'VERIFY_OTP_REJECT';

export const LOGOUT = 'LOGOUT';

export const NOTIFICATION_POP = 'NOTIFICATION_POP';

export const SESSION_TIMEOUT = 'SESSION_TIMEOUT';

export const RESEND_VERIFICATION_MAIL_REQUEST = 'RESEND_VERIFICATION_MAIL_REQUEST';
export const RESEND_VERIFICATION_MAIL_RESOLVE = 'RESEND_VERIFICATION_MAIL_RESOLVE';
export const RESEND_VERIFICATION_MAIL_REJECT = 'RESEND_VERIFICATION_MAIL_REJECT';

export const CHECK_EMAIL_VERIFIED_REQUEST = 'CHECK_EMAIL_VERIFIED_REQUEST';
export const CHECK_EMAIL_VERIFIED_RESOLVE = 'RESEND_VERIFICATION_MAIL_RESOLVE';
export const CHECK_EMAIL_VERIFIED_REJECT = 'CHECK_EMAIL_VERIFIED_REJECT';

export const CHECK_LINK_VERIFIED_REQUEST = 'CHECK_LINK_VERIFIED_REQUEST';
export const CHECK_LINK_VERIFIED_RESOLVE = 'RESEND_VERIFICATION_MAIL_RESOLVE';
export const CHECK_LINK_VERIFIED_REJECT = 'CHECK_LINK_VERIFIED_REJECT';