export const BREAKING_NEWS_REQUEST = 'BREAKING_NEWS_REQUEST';
export const BREAKING_NEWS_RESOLVE = 'BREAKING_NEWS_RESOLVE';
export const BREAKING_NEWS_REJECT = 'BREAKING_NEWS_REJECT';

export const NEWS_BY_GENRE_REQUEST = 'NEWS_BY_GENRE_REQUEST';
export const NEWS_BY_GENRE_RESOLVE = 'NEWS_BY_GENRE_RESOLVE';
export const NEWS_BY_GENRE_REJECT = 'NEWS_BY_GENRE_REJECT';

export const NEWS_ARTICLE_REQUEST = 'NEWS_ARTICLE_REQUEST';
export const NEWS_ARTICLE_RESOLVE = 'NEWS_ARTICLE_RESOLVE';
export const NEWS_ARTICLE_REJECT = 'NEWS_ARTICLE_REJECT';

export const ARTICLES_BY_USER_REQUEST = 'ARTICLES_BY_USER_REQUEST';
export const ARTICLES_BY_USER_RESOLVE = 'ARTICLES_BY_USER_RESOLVE';
export const ARTICLES_BY_USER_REJECT = 'ARTICLES_BY_USER_REJECT';

export const UPDATE_DIVERSITY_VALUE = 'UPDATE_DIVERSITY_VALUE';
export const UPDATE_DIVERSITY_VALUE_PERSONALIZED= 'UPDATE_DIVERSITY_VALUE_PERSONALIZED';

export const GET_USER_ID= 'GET_USER_ID';

 

export const UPDATE_CREATE_IN_PROGRESS_VALUE = 'UPDATE_CREATE_IN_PROGRESS_VALUE';

export const UPDATE_CREATE_IN_PROGRESS_VALUE_NEW = 'UPDATE_CREATE_IN_PROGRESS_VALUE_NEW';

export const UPDATE_NEWS_LETTER_TEMPLATE_DATA ='UPDATE_NEWS_LETTER_TEMPLATE_DATA';



export const UPDATE_USER_ID = 'UPDATE_USER_ID';

export const NEWS_ARTICLE_CONTENT = 'NEWS_ARTICLE_CONTENT';

export const INTERESTED_USER_ID = 'INTERESTED_USER_ID';

export const CLEAR_ARTICLE_PAGE_DATA_ON_SUBMIT = 'CLEAR_ARTICLE_PAGE_DATA_ON_SUBMIT';

export const MAINTAIN_GEN_AI_CHECK = 'MAINTAIN_GEN_AI_CHECK';

export const UPDATE_IS_EMAIL_DATA = 'UPDATE_IS_EMAIL_DATA';

export const UPDATE_PAGE_MAP_VALUE = 'UPDATE_PAGE_MAP_VALUE';

export const UPDATE_ARTICLE_IN_PROGRESS = 'UPDATE_ARTICLE_IN_PROGRESS';

export const UPDATE_SELECTED_GENRE = 'UPDATE_SELECTED_GENRE';

export const CREATE_NEWS_LETTER_REQUEST = 'CREATE_NEWS_LETTER_REQUEST';
export const CREATE_NEWS_LETTER_RESOLVE = 'CREATE_NEWS_LETTER_RESOLVE';
export const CREATE_NEWS_LETTER_REJECT = 'CREATE_NEWS_LETTER_REJECT';

export const ARTICLES_BY_ID_REQUEST = 'ARTICLES_BY_ID_REQUEST';
export const ARTICLES_BY_ID_RESOLVE = 'ARTICLES_BY_ID_RESOLVE';
export const ARTICLES_BY_ID_REJECT = 'ARTICLES_BY_ID_REJECT';

export const INTERACTION_CHECK_REQUEST = 'INTERACTION_CHECK_REQUEST';
export const INTERACTION_CHECK_RESOLVE = 'INTERACTION_CHECK_RESOLVE';
export const INTERACTION_CHECK_REJECT = 'INTERACTION_CHECK_REJECT';

export const GENRE_TYPES_REQUEST = 'GENRE_TYPES_REQUEST';
export const GENRE_TYPES_RESOLVE = 'GENRE_TYPES_RESOLVE';
export const GENRE_TYPES_REJECT = 'GENRE_TYPES_REJECT';